blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

nao:
    resource: "@NAOBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

