user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

nao:
    resource: "@NAOBundle/Resources/config/routing.yml"
    prefix:   /

