user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

nao:
    resource: "@NAOBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
