blog_homepage:
    path:     /blog
    defaults: { _controller: BlogBundle:Default:index }
    requirements:
        _method:  GET|POST

blog_show_old_posts:
    path:     /blog/order/old
    defaults: { _controller: BlogBundle:Posts:show_old_posts }

blog_show_more_posts:
    path:     /blog/{first}/{limit}/{order}
    defaults: { _controller: BlogBundle:Posts:show_more_posts }
    requirements:
        first:    \d+
        limit:    \d+
        order:    "ASC|DESC"

blog_show_post:
    path:     /blog/show/{id}
    defaults: { _controller: BlogBundle:Posts:show_post }
    requirements:
        id:    \d+

blog_refresh:
    path:     /blog/{limit}
    defaults: { _controller: BlogBundle:Default:refresh }

user_article:
    path: /article
    defaults: { _controller: BlogBundle:Default:article }

user_gestion_article:
    path: /gestion-article
    defaults: { _controller: BlogBundle:Default:gestionArticles }

user_delete_article:
    path: /delete-article/{id}
    defaults: { _controller: BlogBundle:Default:deleteArticle }

user_update_post_status:
    path: /update-status-post/{id}/{status}
    defaults: { _controller: BlogBundle:Default:updateArticleStatus }

user_article_update:
    path: /article-editer/{id}
    defaults: { _controller: BlogBundle:Default:articleUpdate }

