user_homepage:
    path: /accueil
    defaults: { _controller: NAOBundle:Default:home }

user_profile:
    path: /mon-profil
    defaults: { _controller: UserBundle:Admin:profil }

user_badge:
    path: /mes-badges
    defaults: { _controller: UserBundle:Admin:badge }

user_gestion_user:
    path: /gestion-membre
    defaults: { _controller: UserBundle:Admin:gestionUser }

user_favoris:
    path: /mes-favoris
    defaults: { _controller: UserBundle:observations:favoris }

user_gestion_observation:
    path: /gestion-observation
    defaults: { _controller: UserBundle:observations:gestionObservations }

user_observation:
    path: /mes-observations
    defaults: { _controller: UserBundle:observations:observation }

user_inscription:
    path: /inscription
    defaults: { _controller: UserBundle:Inscription:register }

delete_observation:
    path: /observation-supprimer/{id}
    defaults: { _controller: UserBundle:observations:deleteObservation }

delete_favori:
    path: /favori-supprimer/{id}
    defaults: { _controller: UserBundle:observations:deleteFavoris }

update_status_observation:
    path: /update-status-obs/{id}/{value}
    defaults: { _controller: UserBundle:observations:updateObservationStatus }

user_update_user_role:
    path: /update_user_role/{id}/{role}
    defaults: { _controller: UserBundle:Admin:updateUserRole }

user_update_user_status:
    path: /update_user_status/{id}/{status}
    defaults: { _controller: UserBundle:Admin:updateUserStatus }

user_upload_picture:
    path: /user_picture
    defaults: { _controller: UserBundle:Admin:userUploadAvatar }


